---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-simple-proxy
spec:
  selector:
    matchLabels:
      application: http-simple-proxy
  template:
    metadata:
      labels:
        application: http-simple-proxy
    spec:
      serviceAccountName: icproxy
      containers:
      - name: proxy
        env:
        - name: ICPROXY_CONFIG
          value: "amqp:myservice=>http:8080,http:8080=>amqp:myservice"
        - name: ICPROXY_POD_SELECTOR
          value: "application=http-simple"
        image: quay.io/gordons/icproxy
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: connect
          mountPath: "/etc/messaging/"
          readOnly: true
      volumes:
      - name: connect
        secret:
          secretName: myrouter
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    application: http-simple-proxy
---
